# Generated by Django 5.0.7 on 2024-07-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_category_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
