# Generated by Django 5.0.7 on 2024-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_service_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
