# Generated by Django 5.0.7 on 2024-07-31 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
