# Generated by Django 5.0.7 on 2024-07-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
        ('Services', '0004_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.category'),
        ),
    ]
