# Generated by Django 5.0.7 on 2024-07-31 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_booking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
