# Generated by Django 5.0.7 on 2024-08-04 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
