# Generated by Django 5.0.7 on 2024-08-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_booking_rating_professionalrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalrating',
            name='score',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
