# Generated by Django 5.1 on 2024-08-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
