# Generated by Django 5.1 on 2024-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0014_booking_pro_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('professional_assigned', 'Professional Assigned'), ('professional_none', 'Professional None'), ('rescheduled', 'Rescheduled'), ('task_done', 'Task Done'), ('payment_done', 'Payment Done'), ('completed', 'Completed'), ('review_done', 'Review Done'), ('professional_not_available', 'Professional not Available')], default='pending', max_length=200),
        ),
    ]
