# Generated by Django 5.1 on 2024-08-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0015_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
