# Generated by Django 5.1 on 2024-08-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0016_booking_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
