# Generated by Django 5.0.7 on 2024-07-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles'),
        ),
    ]
