# Generated by Django 5.0.7 on 2024-07-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_professional_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpstoreprofessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.professional')),
            ],
        ),
    ]
