# Generated by Django 5.0.7 on 2024-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otpstoreprofessional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='earned_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
