# Generated by Django 5.0.7 on 2024-07-19 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customer_is_active_professional_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='otpstore',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='otpstoreprofessional',
            name='otp',
        ),
        migrations.AddField(
            model_name='otpstore',
            name='encrypted_otp',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='otpstoreprofessional',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='professional/profile_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Profile', to='authentication.professional')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user/profile_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
