# Generated by Django 5.0.7 on 2024-07-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customer_profile_remove_otpstore_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstore',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
    ]
