# Generated by Django 5.0.7 on 2024-07-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_otpstore_encryption_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='profile',
        ),
    ]
