# Generated by Django 5.0.7 on 2024-07-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_otpstore_encrypted_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstore',
            name='otp',
        ),
        migrations.AddField(
            model_name='otpstore',
            name='encrypted_otp',
            field=models.BinaryField(null=True),
        ),
    ]
