# Generated by Django 5.0.7 on 2024-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_otpstore_otp_otpstore_encrypted_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstore',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
    ]
