# Generated by Django 5.0.7 on 2024-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_otpstore_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstore',
            name='encrypted_otp',
        ),
        migrations.RemoveField(
            model_name='otpstore',
            name='encryption_key',
        ),
        migrations.AddField(
            model_name='otpstore',
            name='hashed_otp',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
