# Generated by Django 5.0.7 on 2024-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_otpstore_encrypted_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstoreprofessional',
            name='encryption_key',
        ),
        migrations.AddField(
            model_name='otpstoreprofessional',
            name='hashed_otp',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
