# Generated by Django 5.0.7 on 2024-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_otpstoreprofessional_encryption_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstoreprofessional',
            name='hashed_otp',
        ),
        migrations.AddField(
            model_name='otpstoreprofessional',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
