# Generated by Django 5.0.7 on 2024-07-20 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0014_remove_otpstoreprofessional_hashed_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customeruser_permissions',
        ),
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=300)),
                ('profession', models.CharField(max_length=50)),
                ('years_of_exp', models.FloatField()),
                ('adhar_no', models.CharField(max_length=50)),
                ('earned_points', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Otpstoreprofessional',
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
    ]
