# Generated by Django 5.0.7 on 2024-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_customer_date_created_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
