# Generated by Django 5.1 on 2024-08-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_jobprofile_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='address_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
